const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.time,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{tableBase: 0},
	{tableGlow: 0},
	{basePlastic: 0},
	{bulbUnit: 0},
	{powerSource: 0},
	{primaryCoil: 0},
	{secondaryCoil: 0},
	{meterFace: 0},
	{leftCable: 0},
	{leftCableExtra: 0},
	{rightCable: 0},
	{sourcePanel: 0},
	{primaryPanel: 0},
	{secondaryPanel: 0},
	{sliderTrack: 0},
	{sliderKnob: 0},
	{modeSwitch: 0},
	{panelNumber: 0},
	{primaryReading: 0},
	{secondaryReading: 0},
	{voltageReading: 0},
	{powerTap: 0},
	{primaryTap: 0},
	{secondaryTap: 0},
	{bulbTap: 0},
	{meterTap: 0},
	{switchTap: 0},
	{sourceSliderTap: 0},
	{coilSliderTap: 0},
	{menuBtn: 0},
	{meterIcon: 0},
	{bulbIcon: 0},
	{leftAmmeter: 0},
	{rightAmmeter: 0},
	{menuPanel: 0},
	{menuTitle: 0},
	{menuBody: 0},
	{Audio: 0},
	{hintOutline: 0},
	{sourceV: 0},
	{primaryN: 0},
	{secondaryN: 0},
	{modeAC: 0},
	{outputMode: 0},
	{panelMode: 0},
	{menuOpen: 0},
	{dirty: 0},
	{secondaryV: 0},
	{primaryI: 0},
	{secondaryI: 0},
	{frameSource: 0},
	{framePrimary: 0},
	{frameSecondary: 0},
	{frameRightCable: 0},
	{glow: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	tableBase: class extends self.ISpriteInstance {},
	tableGlow: class extends self.ISpriteInstance {},
	basePlastic: class extends self.ISpriteInstance {},
	bulbUnit: class extends self.ISpriteInstance {},
	powerSource: class extends self.ISpriteInstance {},
	primaryCoil: class extends self.ISpriteInstance {},
	secondaryCoil: class extends self.ISpriteInstance {},
	meterFace: class extends self.ISpriteInstance {},
	leftCable: class extends self.ISpriteInstance {},
	leftCableExtra: class extends self.ISpriteInstance {},
	rightCable: class extends self.ISpriteInstance {},
	sourcePanel: class extends self.ISpriteInstance {},
	primaryPanel: class extends self.ISpriteInstance {},
	secondaryPanel: class extends self.ISpriteInstance {},
	sliderTrack: class extends self.ISpriteInstance {},
	sliderKnob: class extends self.ISpriteInstance {},
	modeSwitch: class extends self.ISpriteInstance {},
	panelNumber: class extends self.ITextInstance {},
	primaryReading: class extends self.ITextInstance {},
	secondaryReading: class extends self.ITextInstance {},
	voltageReading: class extends self.ITextInstance {},
	powerTap: class extends self.ISpriteInstance {},
	primaryTap: class extends self.ISpriteInstance {},
	secondaryTap: class extends self.ISpriteInstance {},
	bulbTap: class extends self.ISpriteInstance {},
	meterTap: class extends self.ISpriteInstance {},
	switchTap: class extends self.ISpriteInstance {},
	sourceSliderTap: class extends self.ISpriteInstance {},
	coilSliderTap: class extends self.ISpriteInstance {},
	menuBtn: class extends self.ISpriteInstance {},
	meterIcon: class extends self.ISpriteInstance {},
	bulbIcon: class extends self.ISpriteInstance {},
	leftAmmeter: class extends self.ISpriteInstance {},
	rightAmmeter: class extends self.ISpriteInstance {},
	menuPanel: class extends self.ISpriteInstance {},
	menuTitle: class extends self.ITextInstance {},
	menuBody: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	hintOutline: class extends self.ISpriteInstance {}
}